//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReslangMUI {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.App_GlobalResources.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 關於 的當地語系化字串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 返回 的當地語系化字串。
        /// </summary>
        public static string Back_to {
            get {
                return ResourceManager.GetString("Back_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 返回列表 的當地語系化字串。
        /// </summary>
        public static string Back_to_List {
            get {
                return ResourceManager.GetString("Back_to_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立 的當地語系化字串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新建 的當地語系化字串。
        /// </summary>
        public static string Create_New {
            get {
                return ResourceManager.GetString("Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶銀行帳戶資料維護 的當地語系化字串。
        /// </summary>
        public static string CustomerBankAccountManagement {
            get {
                return ResourceManager.GetString("CustomerBankAccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶聯絡人資料維護 的當地語系化字串。
        /// </summary>
        public static string CustomerContactManagement {
            get {
                return ResourceManager.GetString("CustomerContactManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶資料維護 的當地語系化字串。
        /// </summary>
        public static string CustomerDataManagement {
            get {
                return ResourceManager.GetString("CustomerDataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您確定要刪除此資料? 的當地語系化字串。
        /// </summary>
        public static string Delete_Confirm_Message {
            get {
                return ResourceManager.GetString("Delete_Confirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 詳細資訊 的當地語系化字串。
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯 的當地語系化字串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目錄清單 的當地語系化字串。
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 的當地語系化字串。
        /// </summary>
        public static string oPaginate_sFirst {
            get {
                return ResourceManager.GetString("oPaginate_sFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尾頁 的當地語系化字串。
        /// </summary>
        public static string oPaginate_sLast {
            get {
                return ResourceManager.GetString("oPaginate_sLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下頁 的當地語系化字串。
        /// </summary>
        public static string oPaginate_sNext {
            get {
                return ResourceManager.GetString("oPaginate_sNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上頁 的當地語系化字串。
        /// </summary>
        public static string oPaginate_sPrevious {
            get {
                return ResourceManager.GetString("oPaginate_sPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存 的當地語系化字串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示第 _START_ 至 _END_ 項結果，共 _TOTAL_ 項 的當地語系化字串。
        /// </summary>
        public static string sInfo {
            get {
                return ResourceManager.GetString("sInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示第 0 至 0 項結果，共 0 項 的當地語系化字串。
        /// </summary>
        public static string sInfoEmpty {
            get {
                return ResourceManager.GetString("sInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (從 _MAX_ 項結果過濾) 的當地語系化字串。
        /// </summary>
        public static string sInfoFiltered {
            get {
                return ResourceManager.GetString("sInfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示 _MENU_ 項結果 的當地語系化字串。
        /// </summary>
        public static string sLengthMenu {
            get {
                return ResourceManager.GetString("sLengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處理中... 的當地語系化字串。
        /// </summary>
        public static string sProcessing {
            get {
                return ResourceManager.GetString("sProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜索: 的當地語系化字串。
        /// </summary>
        public static string sSearch {
            get {
                return ResourceManager.GetString("sSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總覽 的當地語系化字串。
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 沒有匹配結果 的當地語系化字串。
        /// </summary>
        public static string sZeroRecords {
            get {
                return ResourceManager.GetString("sZeroRecords", resourceCulture);
            }
        }
    }
}
